--By setting the SCHEMA as FILM there's no need to refer to the SCHEME on each table creation
SET SCHEMA = MOVIEINDEX;

CREATE INDEX COUNTRY_ID 	ON MOVIEINDEX.COUNTRY(NAME)";

CREATE INDEX INCOME 		ON MOVIEINDEX.MOVIE(INCOME);

CREATE INDEX COST		ON MOVIENDEX.MOVIE(COST);

CREATE INDEX MOVIE_INDEX	ON MOVIEINDEX.MOVIE(NAME);
