-- Country
CREATE TABLE COUNTRIES (
    ID      INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME    VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY(ID)
)
IN MOVIEINDEX;

-- Gender
CREATE TABLE GENDERS (
    ID      INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME    VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY(ID)
)
IN MOVIEINDEX;

-- Directors
CREATE TABLE DIRECTORS (
    ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME        VARCHAR(50)      NOT        NULL,
    LASTNAME    VARCHAR(30)      NOT        NULL,
    NATIONALITY INTEGER          NOT        NULL,
    FOREIGN     KEY(NATIONALITY) REFERENCES COUNTRIES(ID),
    PRIMARY     KEY(ID)
)
IN MOVIEINDEX;

-- Actor
CREATE TABLE ACTORS (
    ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME        VARCHAR(50)   NOT        NULL,
    LASTNAME    VARCHAR(30)   NOT        NULL,
    NATIONALITY INTEGER       NOT        NULL,
    FOREIGN     KEY(NATIONALITY) REFERENCES LOCATION(ID),
    PRIMARY     KEY(ID)
)
IN MOVIEINDEX;

-- Actor-Movie
CREATE TABLE ACTORMOVIE (
    ACTORDID INTEGER NOT NULL,
    FOREIGN  KEY(ACTORDID) REFERENCES ACTORS(ID),
    MOVIEID  INTEGER NOT NULL,
    FOREIGN  KEY(MOVIEDID) REFERENCES MOVIES(ID),
)
IN MOVIEINDEX;

-- Studio
CREATE TABLE STUDIO (
    ID       INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME     VARCHAR(30) UNIQUE NOT NULL,
    LOCATION KEY(COUNTRIES),
    PRIMARY  KEY(ID)
)
IN MOVIEINDEX;

-- Clasifications
CREATE TABLE CLASIFICATIONS (
    ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SHORT_NAME  VARCHAR(30) UNIQUE NOT NULL,
    NAME        VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY     KEY(ID)
)
IN MOVIEINDEX;


-- MOVIES
CREATE TABLE MOVIE (
    ID            INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME          VARCHAR(50) NOT        NULL,
    DURATION      INTEGER     NOT        NULL,
    COST          FLOAT       NOT        NULL,
    INCOME        FLOAT       NOT        NULL,
    RELEASE_DATE  DATE        NOT        NULL,
    GENDER        INTEGER     NOT        NULL,
    FOREIGN       KEY(GENDER) REFERENCES GENDERS(ID),
    CLASIFICATION INTEGER     NOT        NULL,
    FOREIGN       KEY(CLASIFICATION) REFERENCES CLASIFICATIONS(ID),
    COUNTRY       INTEGER     NOT        NULL,
    FOREIGN       KEY(COUNTRY) REFERENCES COUNTRIES(ID),
    STUDIO        INTEGER     NOT        NULL,
    FOREIGN       KEY(STUDIO) REFERENCES STUDIOS(ID),
    DIRECTOR      INTEGER     NOT        NULL,
    FOREIGN       KEY(DIRECTOR) REFERENCES DIRECTORS(ID),
    PRIMARY       KEY(ID)
)
IN MOVIEINDEX;
