-- MOVIES
CREATE TABLE MOVIE (
    ID            INTEGER     UNIQUE NOT NULL,
    NAME          VARCHAR(50) NOT NULL,
    DURATION      INTEGER     NOT NULL,
    COST          FLOAT       NOT NULL,
    REVENUE       FLOAT       NOT NULL,
    RELEASE_DATE  DATE        NOT NULL,
    GENDER        KEY(GENDERS),
    CLASIFICATION KEY(CLASIFICATIONS),
    COUNTRY       KEY(COUNTRIES),
    STUDIO        KEY(STUDIOS),
    DIRECTOR      KEY(PERSON),
    PRIMARY KEY   (ID)
)
IN MOVIEINDEX;

-- Person
CREATE TABLE PERSON (
    ID            INTEGER     UNIQUE NOT NULL,
    NAME          VARCHAR(50) NOT NULL,
    LASTNAME      VARCHAR(30) NOT NULL,
    NATIONALITY   VARCHAR(30) NOT NULL,
    ROLE          KEY(ROLES),
    PRIMARY KEY   (ID)
)
IN MOVIEINDEX;

-- Person-Role
CREATE TABLE ROLEPERSON (
    PERSONIDID    KEY(PERSON),
    ROLEID        KEY(ROLE),
)
IN MOVIEINDEX;

-- Role
CREATE TABLE ROLES (
    ID           INTEGER UNIQUE NOT NULL,
    NAME         VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY  (ID)
)
IN MOVIEINDEX;


-- Country
CREATE TABLE COUNTRIES (
    ID           INTEGER UNIQUE NOT NULL,
    NAME         VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY  (ID)
)
IN MOVIEINDEX;

-- Gender
CREATE TABLE GENDERS (
    ID           INTEGER UNIQUE NOT NULL,
    NAME         VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY  (ID)
)
IN MOVIEINDEX;

-- Studio
CREATE TABLE STUDIO (
    ID           INTEGER UNIQUE NOT NULL,
    NAME         VARCHAR(30) UNIQUE NOT NULL,
    LOCATION     VARCHAR(30) NOT NULL,
    PRIMARY KEY  (ID)
)
IN MOVIEINDEX;
