-- Get movies by country
CREATE VIEW COUNTRY_MOVIES (COUNTRY, MOVIENAME, RELEASE_DATE)
    AS SELECT COUNTRIES.NAME, MOVIE.NAME, RELEASE_DATE
    FROM MOVIE, COUNTRIES
    WHERE MOVE.COUNTRY = COUNTRIES.ID
    ORDER BY COUNTRY;

-- Get the 10 movies with the highest income
CREATE VIEW TOP_INCOME_MOVIES (
    NAME,
    GENDER,
    DURATION,
    COST,
    INCOME,
    RELEASE_DATE,
    CLASIFICATION,
    STUDIO,
    DIRECTOR
)
    AS SELECT
        MOVIE.NAME,
        GENDERS.NAME,
        MOVIE.DURATION,
        MOVIE.COST,
        MOVIE.INCOME,
        MOVIE.RELEASE_DATE,
        CLASIFICATION.NAME,
        STUDIO.NAME,
        DIRECTORS.NAME
    FROM
        MOVIE,
        GENDER,
        STUDIO,
        DIRECTORS,
        CLASIICATION
    WHERE
        MOVE.GENDER = GENDER.ID AND
        MOVIE.CLASIFICATION = CLASIFICATION.ID AND
        MOVIE.DIRECTOR = DIRECTORS.ID AND
        MOVIE.STUDIO = STUDIO.ID
    ORDER BY INCOME DESC
    FETCH FIRST 10 ROWS ONLY;

-- Get the 10 movies with the lowest income
CREATE VIEW LOWEST_INCOME_MOVIES (
    NAME,
    GENDER,
    DURATION,
    COST,
    INCOME,
    RELEASE_DATE,
    CLASIFICATION,
    STUDIO,
    DIRECTOR
)
    AS SELECT
        MOVIE.NAME,
        GENDERS.NAME,
        MOVIE.DURATION,
        MOVIE.COST,
        MOVIE.INCOME,
        MOVIE.RELEASE_DATE,
        CLASIFICATION.NAME,
        STUDIO.NAME,
        DIRECTORS.NAME
    FROM
        MOVIE,
        GENDER,
        STUDIO,
        DIRECTORS,
        CLASIICATION
    WHERE
        MOVE.GENDER = GENDER.ID AND
        MOVIE.CLASIFICATION = CLASIFICATION.ID AND
        MOVIE.DIRECTOR = DIRECTORS.ID AND
        MOVIE.STUDIO = STUDIO.ID
    ORDER BY INCOME ASC
    FETCH FIRST 10 ROWS ONLY;

-- Get the 10 most expensive movies
CREATE VIEW TOP_EXPENSIVE_MOVIES (
    NAME,
    GENDER,
    DURATION,
    COST,
    INCOME,
    RELEASE_DATE,
    CLASIFICATION,
    STUDIO,
    DIRECTOR
)
    AS SELECT
        MOVIE.NAME,
        GENDERS.NAME,
        MOVIE.DURATION,
        MOVIE.COST,
        MOVIE.INCOME,
        MOVIE.RELEASE_DATE,
        CLASIFICATION.NAME,
        STUDIO.NAME,
        DIRECTORS.NAME
    FROM
        MOVIE,
        GENDER,
        STUDIO,
        DIRECTORS,
        CLASIICATION
    WHERE
        MOVE.GENDER = GENDER.ID AND
        MOVIE.CLASIFICATION = CLASIFICATION.ID AND
        MOVIE.DIRECTOR = DIRECTORS.ID AND
        MOVIE.STUDIO = STUDIO.ID
    ORDER BY COST DESC
    FETCH FIRST 10 ROWS ONLY;

-- TODO: Get the studio with more movies
CREATE VIEW MOST_PRODUCTIVE_STUDIOS (NAME, LOCATION)
    AS SELECT
        STUDIO.NAME,
        STUDIO.LOCATION
    FROM
        STUDIO,
        MOVIE,
    WHERE
        MOVE.GENDER = GENDER.ID AND
        MOVIE.CLASIFICATION = CLASIFICATION.ID AND
        MOVIE.DIRECTOR = DIRECTORS.ID AND
        MOVIE.STUDIO = STUDIO.ID
    ORDER BY COST DESC
    FETCH FIRST 10 ROWS ONLY;
