-- Create 5 views

CREATE VIEW COUNTRY_MOVIES (COUNTRY, MOVIENAME, RELEASE_DATE)
  AS SELECT COUNTRIES.NAME, MOVIE.NAME, RELEASE_DATE
  FROM MOVIE, COUNTRIES
  WHERE MOVE.COUNTRY = COUNTRIES.ID;

CREATE VIEW COUNTRY_MOVIES (COUNTRY, MOVIENAME, RELEASE_DATE)
  AS SELECT COUNTRIES.NAME, MOVIE.NAME, RELEASE_DATE
  FROM MOVIE, COUNTRIES
  WHERE MOVE.COUNTRY = COUNTRIES.ID;

CREATE VIEW COUNTRY_MOVIES (COUNTRY, MOVIENAME, RELEASE_DATE)
  AS SELECT COUNTRIES.NAME, MOVIE.NAME, RELEASE_DATE
  FROM MOVIE, COUNTRIES
  WHERE MOVE.COUNTRY = COUNTRIES.ID;

CREATE VIEW COUNTRY_MOVIES (COUNTRY, MOVIENAME, RELEASE_DATE)
  AS SELECT COUNTRIES.NAME, MOVIE.NAME, RELEASE_DATE
  FROM MOVIE, COUNTRIES
  WHERE MOVE.COUNTRY = COUNTRIES.ID;

CREATE VIEW COUNTRY_MOVIES (COUNTRY, MOVIENAME, RELEASE_DATE)
  AS SELECT COUNTRIES.NAME, MOVIE.NAME, RELEASE_DATE
  FROM MOVIE, COUNTRIES
  WHERE MOVE.COUNTRY = COUNTRIES.ID;
