--SET TERMINATOR @
-- Stored procedures

--By setting the SCHEMA as FILM there's no need to refer to the SCHEME on each table creation
--SET SCHEMA = MOVIEINDEX;

CREATE or REPLACE PROCEDURE MOVIEINDEX.MOVIE_GENDER ( IN MOVIENAME VARCHAR(50), OUT GENDERS INT )
LANGUAGE SQL
P5:BEGIN
    DECLARE MOVIEID int;

    DECLARE cursor1 CURSOR FOR
        SELECT ID FROM MOVIEINDEX.MOVIE WHERE MOVIEINDEX.MOVIE.NAME = MOVIENAME;
    OPEN cursor1;
        FETCH FROM cursor1 INTO MOVIEID;
    CLOSE cursor1;

    DECLARE cursor2 CURSOR FOR
        SELECT COUNT(*) AS GENDERS_IN
            FROM MOVIEINDEX.MOVIE, MOVIEINDEX.GENDER_MOVIE, MOVIEINDEX.GENDER
            WHERE MOVIEINDEX.MOVIE.ID = MOVIEID AND MOVIEINDEX.GENDER_MOVIE.MOVIEDID = MOVIEID AND MOVIEINDEX.GENDER.ID = MOVIEINDEX.GENDER_MOVIE.GENDERID;
    OPEN cursor2;
        FETCH FROM cursor2 INTO GENDERS;
    CLOSE cursor2;
END P5
@

