--SET TERMINATOR @
-- Stored procedures

--By setting the SCHEMA as FILM there's no need to refer to the SCHEME on each table creation
--SET SCHEMA = MOVIEINDEX;

CREATE or REPLACE PROCEDURE MOVIEINDEX.MOVIE_GENDER ( IN MOVIENAME VARCHAR(50), IN GENDERNAME VARCHAR(50) )
LANGUAGE SQL
P1:BEGIN
    DECLARE GENDER_ID int;
    DECLARE MOVIE_ID int;

    DECLARE cursor1 CURSOR FOR SELECT ID FROM MOVIEINDEX.MOVIE WHERE MOVIENAME = MOVIEINDEX.MOVIE.NAME;
    DECLARE cursor2 CURSOR FOR SELECT ID FROM MOVIEINDEX.GENDER WHERE GENDERNAME = MOVIEINDEX.GENDER.NAME;
    OPEN cursor1;
        FETCH FROM cursor1 INTO GENDER_ID;
    CLOSE cursor1;
    OPEN cursor2;
        FETCH FROM cursor2 INTO MOVIE_ID;
    CLOSE cursor2;

    INSERT INTO MOVIEINDEX.GENDER_MOVIE (GENDERDID, MOVIEDID) VALUES (GENDER_ID, MOVIE_ID);
END P1
@
